controller_list:
  - name: fake_left_arm_controller
    joints:
      - shoulder_left_axis0
      - shoulder_left_axis1
      - shoulder_left_axis2
      - elbow_left
      - wrist_left_axis0
      - wrist_left_axis1
      - wrist_left_axis2
  - name: fake_right_arm_controller
    joints:
      - shoulder_right_axis0
      - shoulder_right_axis1
      - shoulder_right_axis2
      - elbow_right
      - wrist_right_axis0
      - wrist_right_axis1
      - wrist_right_axis2