# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - neck_axis0
    - neck_axis1
    - neck_axis2
    - zed_camera_mount
    - zed_camera_left
    - zed_camera_right
    - shoulder_left_axis0
    - shoulder_left_axis1
    - shoulder_left_axis2
    - elbow_left
    - wrist_left_axis0
    - wrist_left_axis1
    - wrist_left_axis2
    - hand_left_index_joint0
    - hand_left_little_joint1
    - hand_left_little_joint2
    - hand_left_little_joint0
    - hand_left_index_joint1
    - hand_left_index_joint2
    - hand_left_middle_joint0
    - hand_left_middle_joint1
    - hand_left_middle_joint2
    - hand_left_ring_joint0
    - hand_left_ring_joint1
    - hand_left_ring_joint2
    - hand_left_thumb_joint0
    - hand_left_thumb_joint1
    - hand_left_thumb_joint2
    - shoulder_right_axis0
    - shoulder_right_axis1
    - shoulder_right_axis2
    - elbow_right
    - wrist_right_axis0
    - wrist_right_axis1
    - wrist_right_axis2
    - hand_right_index_joint0
    - hand_right_index_joint1
    - hand_right_index_joint2
    - hand_right_little_joint0
    - hand_right_little_joint1
    - hand_right_little_joint2
    - hand_right_middle_joint0
    - hand_right_middle_joint1
    - hand_right_middle_joint2
    - hand_right_ring_joint0
    - hand_right_ring_joint1
    - hand_right_ring_joint2
    - hand_right_thumb_joint0
    - hand_right_thumb_joint1
    - hand_right_thumb_joint2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - hand_left_index_joint0
      - hand_left_little_joint1
      - hand_left_little_joint2
      - hand_left_little_joint0
      - hand_left_index_joint1
      - hand_left_index_joint2
      - hand_left_middle_joint0
      - hand_left_middle_joint1
      - hand_left_middle_joint2
      - hand_left_ring_joint0
      - hand_left_ring_joint1
      - hand_left_ring_joint2
      - hand_left_thumb_joint0
      - hand_left_thumb_joint1
      - hand_left_thumb_joint2
  - name: right_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - hand_right_index_joint0
      - hand_right_index_joint1
      - hand_right_index_joint2
      - hand_right_little_joint0
      - hand_right_little_joint1
      - hand_right_little_joint2
      - hand_right_middle_joint0
      - hand_right_middle_joint1
      - hand_right_middle_joint2
      - hand_right_ring_joint0
      - hand_right_ring_joint1
      - hand_right_ring_joint2
      - hand_right_thumb_joint0
      - hand_right_thumb_joint1
      - hand_right_thumb_joint2